DROP TABLE IF EXISTS NFT_DATA;
DROP TABLE IF EXISTS NFT_ATTRIBUTES;
DROP TABLE IF EXISTS PERCENTAGE_DATA;
DROP TABLE IF EXISTS NFT_TOTALS;

CREATE TABLE NFT_DATA
(
    NFT_ID  INT PRIMARY KEY AUTO_INCREMENT,
    NFT_NAME VARCHAR(30),
    NFT_DESCRIPTION VARCHAR(256),
    NFT_IMAGE VARCHAR(256),
    NFT_DNA VARCHAR(256),
    NFT_EDITION INT,
    NFT_DATE BIGINT
);

CREATE TABLE NFT_ATTRIBUTES
(
    ATTRIBUTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NFT_ID INT UNIQUE NOT NULL,
    BACKGROUND VARCHAR(30),
    CART_COLOR VARCHAR(30),
    CART_ART VARCHAR(30),
    PRICE_STICKER VARCHAR(30),
    CART_CONDITION VARCHAR(30),
    FOREIGN KEY(NFT_ID) REFERENCES NFT_DATA(NFT_ID)
);

CREATE TABLE NFT_TOTALS
(
    TOTAL_ID INT PRIMARY KEY AUTO_INCREMENT,
    ATTRIBUTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    TOTAL_NFT_ID INT UNIQUE NOT NULL,
    TOTAL_BACKGROUND VARCHAR(30),
    TOTAL_CART_COLOR VARCHAR(30),
    TOTAL_CART_ART VARCHAR(30),
    TOTAL_PRICE_STICKER VARCHAR(30),
    TOTAL_CART_CONDITION VARCHAR(30),
    FOREIGN KEY(NFT_ID) REFERENCES NFT_DATA(NFT_ID)
);

CREATE TABLE PERCENTAGE_DATA
(
    PERCENTAGE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NFT_ID INT UNIQUE NOT NULL,
    PERCENTAGE_BACKGROUND VARCHAR(30),
    PERCENTAGE_CART_COLOR VARCHAR(30),
    PERCENTAGE_CART_ART VARCHAR(30),
    PERCENTAGE_PRICE_STICKER VARCHAR(30),
    PERCENTAGE_CART_CONDITION VARCHAR(30),
    FOREIGN KEY(NFT_ID) REFERENCES NFT_DATA(NFT_ID)
);
